all: dappnet toolbar

dappnet: dappnet.m
	clang -framework Foundation -framework Cocoa -framework WebKit -framework QuartzCore dappnet.m -o dappnet

toolbar: toolbar.m
	clang -framework Foundation -framework Cocoa -framework WebKit -framework QuartzCore toolbar.m -o toolbar